name: .NET Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build

      - name: Install CSharpier
        run: dotnet tool install -g csharpier

      - name: Add Tool Path
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Check Formatting
        run: csharpier check .

      - name: Build Docker Image
        run: docker build -t cicd-webapi .

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Deploy Step
        run: echo "Deploying application..."